import { Inter } from "next/font/google";
import "./globals.css";

import { ThemeContextProvider } from "@/context/ThemeContext";
import ThemeProvider from "@/providers/ThemeProvider";
import ToastNotificationContainer from "@/components/ToastNotificationComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "B2xclusive",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeContextProvider>
          <ThemeProvider>
            <section className="w-full mx-auto">
              <ToastNotificationContainer />

              {children}
            </section>
          </ThemeProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
